<?php

/**
 * @file
 * Provides the ability to embed gists from Github.
 *
 * This module provides an input filter to add a gist (from Github) anywhere
 * input filters are accepted. You have the option of replacing the filter tag
 * with a link to the gist or embedding the gist itself.
 */


/**
 * Implementation of hook_filter_info().
 */
function gist_filter_filter_info() {
  $filters['gist_filter'] = array(
    'title' => t('Gist filter (Github Gists)'),
    'description' => t('Substitutes [gist:xx] tags with the gist located at http://gist.github.com/xx.'),
    'process callback'  => 'gist_filter_gist_filter_process',
    'default settings' => array(
      'gist_filter_display_method' => 'embed',
    ),
    'settings callback' => 'gist_filter_gist_filter_settings',
    'tips callback' => 'gist_filter_filter_tips',
    'cache' => TRUE,
  );
  return $filters;
}

/**
 * Process callback for hook_filter_info().
 */
function gist_filter_gist_filter_process($text, $filter, $format) {
  $display = $filter->settings['gist_filter_display_method'];
  return preg_replace('@\[gist\:(\d+)\]@', _gist_display('$1', $display), $text);
}


/**
 * Settings callback for gist_filter.
 */
function gist_filter_gist_filter_settings($form, $form_state, $filter, $format, $defaults) {
  $settings['gist_filter_display_method'] = array(
    '#title' => t('Gist display method'),
    '#type' => 'select',
    '#options' => array(
      'embed' => t('Embed'),
      'link' => t('Link'),
    ),
    '#default_value' => isset($filter->settings['gist_filter_display_method']) ? $filter->settings['gist_filter_display_method'] : $defaults['gist_filter_display_method'],
  );
  return $settings;
}

/**
 * Implements hook_filter_tips().
 */
function gist_filter_filter_tips($filter, $format, $long = FALSE) {
  $display = $filter->settings['gist_filter_display_method'];
  $action = $display == 'embed' ? t('embed the gist') : t('create a link to the gist');
  return t('Use [gist:####] where #### is your gist number to %action.', array('%action' => $action));
}

/**
 * Replace the text with embedded script or link.
 */
function _gist_display($gist, $display) {
  $url = 'http://gist.github.com/' . $gist;
  switch ($display) {
    case 'embed':
      return '<script src="' . $url . '.js"></script>';
    case 'link':
      return l($url, $url);
  }
}
